### ISSUE TITLE
I am Failing to create a IWorkBook object

### ISSUE THREAD

**Issue by ilanle** [DxCx/ts-xlsx#19]
Thanks for this,
I am having some trouble with it.

In the js-xlsx examples, they use this code to create a workbook

var wb = new Workbook(), ws = sheet_from_array_of_arrays(data);
/* add worksheet to workbook */
wb.SheetNames.push(ws_name);
wb.Sheets[ws_name] = ws;
var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true, type: 'binary'});

I try to import IWorkBook

and then
let wb:IWorkBook

but I end up with an undefined object.

Can you please give a really short example of how I create an empty workbook?
I have an array of arrays and wish to save a workbook with a single worksheet

thanks

**Comment by DxCx** [comment]
hey @ilanle ,
this is typescript wrapper for [js-xlsx](https://github.com/SheetJS/js-xlsx) that embeds typings correctly for typescript.
also, we are not in deprecation stages because xlsx are adding typings internally so there will be no reason to keep maintain both as i believe @SheetJS doing great work to make that happen.

with that said, you can go over https://github.com/SheetJS/js-xlsx#writing-workbooks and see there are great examples there on how to do it,
if it still doesn't work i suggest to open an issue there.. 👍
